export const ERROR_CODES = {
  INVALID_CREDENTIALS: "INVALID_CREDENTIALS",
  USER_NOT_FOUND: "USER_NOT_FOUND",
  ORDER_NOT_FOUND: "ORDER_NOT_FOUND",
  INSUFFICIENT_FUNDS: "INSUFFICIENT_FUNDS",
  INVALID_ORDER: "INVALID_ORDER",
} as const;

export const ERROR_MESSAGES = {
  [ERROR_CODES.INVALID_CREDENTIALS]: "Invalid email or password",
  [ERROR_CODES.USER_NOT_FOUND]: "User not found",
  [ERROR_CODES.ORDER_NOT_FOUND]: "Order not found",
  [ERROR_CODES.INSUFFICIENT_FUNDS]: "Insufficient funds",
  [ERROR_CODES.INVALID_ORDER]: "Invalid order parameters",
};
