module.exports = {
  apps: [
    {
      name: "xpro-api",
      script: "dist/server.js",
      instances: "max",
      exec_mode: "cluster",
      env: {
        NODE_ENV: "production",
        PORT: 3001,
        DATABASE_URL: process.env.DATABASE_URL,
        REDIS_URL: process.env.REDIS_URL,
        JWT_SECRET: process.env.JWT_SECRET,
        CORS_ORIGIN: process.env.CORS_ORIGIN || "https://yourdomain.com",
        LOG_LEVEL: "info",
      },
      env_production: {
        NODE_ENV: "production",
      },
      error_file: "./logs/err.log",
      out_file: "./logs/out.log",
      log_file: "./logs/combined.log",
      time: true,
      max_memory_restart: "1G",
      restart_delay: 4000,
      max_restarts: 10,
      min_uptime: "10s",
      watch: false,
      ignore_watch: ["node_modules", "logs", "coverage"],
      env_production: {
        NODE_ENV: "production",
      },
    },
    {
      name: "xpro-trading-engine",
      script: "main.py",
      interpreter: "python3",
      instances: 1,
      exec_mode: "fork",
      cwd: "/path/to/python/engine",
      env: {
        PYTHONPATH: "/path/to/python/engine",
        DATABASE_URL: process.env.DATABASE_URL,
        REDIS_URL: process.env.REDIS_URL,
        LOG_LEVEL: "INFO",
      },
      error_file: "./logs/trading-engine-err.log",
      out_file: "./logs/trading-engine-out.log",
      log_file: "./logs/trading-engine-combined.log",
      time: true,
      max_memory_restart: "500M",
      restart_delay: 4000,
      max_restarts: 5,
      min_uptime: "30s",
      watch: false,
    },
  ],
};
